package profileio

import (
	"os"
	"strings"
	"testing"

	"github.com/crmne/hyprmoncfg/internal/profile"
)

func TestSaveWithSidecarsWritesJSONConfAndLua(t *testing.T) {
	store := profile.NewStore(t.TempDir())
	p := profile.New("Desk Dock", []profile.OutputConfig{{
		Key:         "dell|u2720q|a1",
		MatchKey:    "dell|u2720q|a1",
		Name:        "DP-1",
		Description: "Dell U2720Q",
		Make:        "Dell",
		Model:       "U2720Q",
		Serial:      "A1",
		Enabled:     true,
		Width:       2560,
		Height:      1440,
		Refresh:     144,
		Scale:       1,
	}})
	p.Workspaces = profile.WorkspaceSettings{
		Enabled:       true,
		Strategy:      profile.WorkspaceStrategySequential,
		MaxWorkspaces: 1,
		GroupSize:     1,
		MonitorOrder:  []string{"dell|u2720q|a1"},
	}

	if err := SaveWithSidecars(store, p); err != nil {
		t.Fatalf("save with sidecars: %v", err)
	}

	paths := store.PathsForName("Desk Dock")
	for _, path := range []string{paths.JSON, paths.Conf, paths.Lua} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected %s to exist: %v", path, err)
		}
	}

	saved, err := store.Load("Desk Dock")
	if err != nil {
		t.Fatalf("load saved profile: %v", err)
	}
	if got := saved.Outputs[0].Description; got != "Dell U2720Q" {
		t.Fatalf("expected description to round-trip, got %q", got)
	}

	conf := readFile(t, paths.Conf)
	for _, want := range []string{
		"# Generated by hyprmoncfg",
		"monitorv2 {",
		"output = desc:Dell U2720Q",
		"workspace = 1, monitor:desc:Dell U2720Q, default:true, persistent:true",
	} {
		if !strings.Contains(conf, want) {
			t.Fatalf("exported conf missing %q:\n%s", want, conf)
		}
	}

	lua := readFile(t, paths.Lua)
	for _, want := range []string{
		"-- Generated by hyprmoncfg",
		"hl.monitor({",
		`output = "desc:Dell U2720Q",`,
		`hl.workspace_rule({ workspace = "1", monitor = "desc:Dell U2720Q", default = true, persistent = true })`,
	} {
		if !strings.Contains(lua, want) {
			t.Fatalf("exported lua missing %q:\n%s", want, lua)
		}
	}
}

func TestStoreDeleteRemovesProfileSidecars(t *testing.T) {
	store := profile.NewStore(t.TempDir())
	p := profile.New("Desk Dock", []profile.OutputConfig{{
		Key:     "dp-1",
		Name:    "DP-1",
		Enabled: true,
		Width:   1920,
		Height:  1080,
		Scale:   1,
	}})
	if err := SaveWithSidecars(store, p); err != nil {
		t.Fatalf("save with sidecars: %v", err)
	}

	paths := store.PathsForName("Desk Dock")
	if err := store.Delete("Desk Dock"); err != nil {
		t.Fatalf("delete profile: %v", err)
	}

	for _, path := range []string{paths.JSON, paths.Conf, paths.Lua} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("expected %s to be deleted, stat err=%v", path, err)
		}
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(content)
}
